### ISSUE TITLE
Techniques for improving TED pass-through volume

### ISSUE THREAD

**Issue by SteveGuidi** [SukkoPera/ReSeed#5]
This isn't an issue but more of a question or discussion topic.

I noticed that music playback through the TED generally has low volume (i.e. no speakers hooked up to the card's audio-out port).  I have a feeling that this is normal, but I wanted to confirm.  Note that if I maximize the volume via the volume resistor, I get marginal volume increase via the TED, but get a much larger gain through audio-out.

I suppose I could use a higher-gain transistor for the amplifier -- I'm using a 2N3904 with typical hFE of 100 @10mA.  (I got lazy here and just used this BJT as I have several on hand -- I didn't see that the recommended transistors have a higher gain!)  That said, does the transistor amplify the TED pass-through signal too?

**Comment by SukkoPera** [comment]
First of all, playback does not happen "through the TED" (I mean the TED chip). Rather, the SID output fed back into the machine through the EXT_AUDIO pin of the Expansion connector gets **mixed** with the TED audio output. This can be seen clearly from [the C16 schematics](https://github.com/SukkoPera/LittleSixteen/blob/master/output/schematics.pdf).

Second: yes, the volume control on the ReSeed board affects both the jack output and the signal that is fed back into the machine.

That said, I generally set it at about 90% of full range and I don't feel the volume is low at all. I have never tested the 2N3904 transistor though, all my boards have a BC547 or a 2SC1815. I see that the 2N3904 has an EBC pinout, so it looks like it should be installed **in the bottom footprint of Q1 but with the opposite orientation** (i.e. flat side towards the top of the board), did you install it like that?

If it's still low, I don't think it is necessary to use a transistor with a higher gain, it could be enough to play with the values of R4 and R5 to change the gain, even though I'm not exactly sure how :).

As a side note, the original SIDcard design from Solder had a 2-stage output amplifier circuit but it was often criticized for distorting the sound. We assumed it was mostly meant for driving passive external speakers, since our testing showed that the output volume through the EXT_AUDIO pin was already sufficient even without the 2nd stage. Since today it's much more common to have powered speakers, we decided to remove the 2nd stage, falling back to the original C64 circuit (plus volume control). But all of this means we went through quite some testing of the audio levels :).

**Comment by SteveGuidi** [comment]
Thank you for the feedback, @SukkoPera.  The more I experiment with this, the more confident I get that thus is an issue with the factory single swipe TED socket.  I have an issue where if I tap or bump my C16, then the video shuts off temporarily or the machine crashes.  it does happen all the time, but I've found that I can get the mixed audio to drop in volume precisely when these video issues happen.

I'm pretty sure there is nothing wrong with the SID card or any of thr components installed on it, so the next step will be to replace the TED socket.

**Comment by SukkoPera** [comment]
Well, that could justify if TED audio has low volume, but it shouldn't affect the audio coming from the SID.
